### ISSUE TITLE
hosts unit tests reveal polymath warning

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/pds-oops#20]
Running `hosts.juno.junocam.Test_Juno_Junocam_Backplane_Exercises.runTest` produces the warning:

```
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  result[self.vals == top] -= 1
```

`polymath` should be fixed so that this will not be a problem in the future.

**Comment by jnspitale** [comment]
This is actually a problem with Mark's recent updates to the observation classes rather than with polymath.  The 'top' argument  should have only one element, but many of those modules are calling it with two.  I'll remind Mark to have a look at it.
