### ISSUE TITLE
Use Body.has_rings() to allow backplane unit tests requiring ring frames

### ISSUE THREAD

**Issue by jnspitale** [SETI/pds-oops#29]
The code for these tests is currently commented out in oops/backplane/ pending the addition of Body.has_rings() (see issue #28).  The code can be searched with the string "TODO: use Body.has_rings() once Mark has created it".

**Comment by markshowalter** [comment]
The correct way to determine if a body has a default ring is "if body.ring_frame" or "if body.ring_frame is not None". This is similar to how we currently test for whether a Body has a surface or defined gravity field. I think this is OK, at least for the time being.

**Comment by jnspitale** [comment]
Resolved as suggested by Mark
