### ISSUE TITLE
Re-create lost PDS3 tools module in hosts/

### ISSUE THREAD

**Issue by jnspitale** [SETI/pds-oops#43]
Created module of PDS3 utilities in 11/22; seems to have disappeared form all branches since then.  Commit notes were as follows:

  - added pds3.py to hosts/, defining PDS3 class
  - added find_label(), clean_label, and get_label() to PDS3 class
  - changed junocam, jiram, and voyager ISS to use PDS3.get_label()
  - added filespec and basename attributes to voyager iss
  - fixed voyager ISS to work with embedded VICAR label

Presumably the other Voyager ISS changes were lost as well.

**Comment by rfrenchseti** [comment]
I see no evidence this commit ever existed (email, Slack, git history). I have my own version of the VGISS changes I can give you if you need them.

**Comment by jnspitale** [comment]
It was apparently never pushed.  I suspect it got lost in some branch shuffling.  It's very annoying.  Once we get Mark's gold master stuff merged into master I'll rebuild it and do a pull request and get it into master.


________________________________

**Comment by jnspitale** [comment]
[x] re-write code
[ ] add unit tests
[ ] merge master into pds3
[ ] creat pull request
[ ] merge into master
